-- Create indexes & foreign keys

ALTER TABLE NURSERY_ANALYSIS
ADD CONSTRAINT fk_fac
FOREIGN KEY (FACILITY_ID)
REFERENCES FACILITY(FACILITY_ID);

ALTER TABLE NURSERY_ANALYSIS
ADD CONSTRAINT fk_clim
FOREIGN KEY (CLIMATE_ID)
REFERENCES CLIMATE(CLIMATE_ID);

ALTER TABLE NURSERY_ANALYSIS
ADD CONSTRAINT fk_chem
FOREIGN KEY (CHEMICAL_ID)
REFERENCES CHEMICAL(CHEMICAL_ID);

ALTER TABLE NURSERY_ANALYSIS
ADD CONSTRAINT fk_loc
FOREIGN KEY (LOCATION_ID)
REFERENCES LOCATION(LOCATION_ID);

CREATE INDEX idx1
ON NURSERY_ANALYSIS(FACILITY_ID);

CREATE INDEX idx2
ON NURSERY_ANALYSIS(CLIMATE_ID);

CREATE INDEX idx3
ON NURSERY_ANALYSIS(CHEMICAL_ID);

CREATE INDEX idx4
ON NURSERY_ANALYSIS(LOCATION_ID);
